name: Economy
version: 1.1.0
author: DanMetzkr
api: 3.0.0
main: skycubes\economy\Economy
description: Adiciona suporte a economia no servidor
commands:
  economy:
    description: Comando principal
    usage: /economy
  carteira:
    description: Detalha a carteira do jogador
    usage: /carteira
    aliases:
      - money
      - bal
  pagar:
    description: Enviar dinheiro a um jogador
    usage: /pagar